nodeLinker: node-modules

packageExtensions:
  express@*:
    dependencies:
      cookie-parser: '*'
      morgan: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg-plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

