nodeLinker: pnp

packageExtensions:
  express@*:
    dependencies:
      cookie-parser: "*"
      morgan: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg-plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpFallbackMode: all

pnpMode: strict
