nodeLinker: pnp

packageExtensions:
  express@*:
    dependencies:
      cookie-parser: '*'
      morgan: '*'

pnpFallbackMode: all

pnpMode: strict

plugins:
  - path: .yarn/plugins/@yarnpkg-plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
